//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorApp.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorApp.Client.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER.
        /// </summary>
        public static string GameboardLose {
            get {
                return ResourceManager.GetString("GameboardLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next word in.
        /// </summary>
        public static string GameboardNextWordCountdown {
            get {
                return ResourceManager.GetString("GameboardNextWordCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word was.
        /// </summary>
        public static string GameboardTheWordWas {
            get {
                return ResourceManager.GetString("GameboardTheWordWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WIN.
        /// </summary>
        public static string GameboardWin {
            get {
                return ResourceManager.GetString("GameboardWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough letters.
        /// </summary>
        public static string GameManagerNotEnoughLetters {
            get {
                return ResourceManager.GetString("GameManagerNotEnoughLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word does not exist.
        /// </summary>
        public static string GameManagerWordDoesNotExist {
            get {
                return ResourceManager.GetString("GameManagerWordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string HeaderChangeLanguage {
            get {
                return ResourceManager.GetString("HeaderChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help.
        /// </summary>
        public static string HeaderShowHelp {
            get {
                return ResourceManager.GetString("HeaderShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics.
        /// </summary>
        public static string HeaderShowStatistics {
            get {
                return ResourceManager.GetString("HeaderShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL.
        /// </summary>
        public static string KeyboardDel {
            get {
                return ResourceManager.GetString("KeyboardDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        public static string KeyboardSend {
            get {
                return ResourceManager.GetString("KeyboardSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best streak.
        /// </summary>
        public static string StatsBestStreak {
            get {
                return ResourceManager.GetString("StatsBestStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current streak.
        /// </summary>
        public static string StatsCurrentStreak {
            get {
                return ResourceManager.GetString("StatsCurrentStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        public static string StatsGamesPlayed {
            get {
                return ResourceManager.GetString("StatsGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won %.
        /// </summary>
        public static string StatsGamesWonPercent {
            get {
                return ResourceManager.GetString("StatsGamesWonPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT DISTRIBUTION.
        /// </summary>
        public static string StatsResultDistribution {
            get {
                return ResourceManager.GetString("StatsResultDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
    }
}
